#!/usr/bin/env bash
# performing 301 moved permanently

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacing="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com/ permanent;"

sudo sed -i "s/server_name _;/$string_for_replacing/" /etc/nginx/sites-enabled/default

sudo service nginx restart
