#!/usr/bin/env bash
# This Bash script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.

idx=0

while [ $idx -lt 10 ]
do
  if [ $idx -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( idx++ ))
done
