#!/usr/bin/env bash
# This Bash script loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

check=0

while [ $check -lt 10 ]
do
  if [ $check -eq 3 ]
  then
    echo "bad luck"
  elif [ $check -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( check++ ))
done
