#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash.


list=$(ls)
for g in $list; do
  echo "$g" | cut -d '-' -f2
done
